{
 "title": "Dashboard 0",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU util %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[5m])) * 100)\r",
     "legendFormat": "CPU utilization"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}\r",
     "legendFormat": "LA1"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}\r",
     "legendFormat": "LA5"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}\r",
     "legendFormat": "LA15"
    }
   ]
  },
  {
   "title": "Disk space - free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\r\n  node_filesystem_avail_bytes{\r\n    job=\"nodeexporter\",\r\n    fstype!~\"tmpfs|overlay|squashfs|ramfs\",\r\n    mountpoint!~\"/run/credentials/.*\"\r\n  }\r\n/\r\n  node_filesystem_size_bytes{\r\n    job=\"nodeexporter\",\r\n    fstype!~\"tmpfs|overlay|squashfs|ramfs\",\r\n    mountpoint!~\"/run/credentials/.*\"\r\n  }\r\n) * 100\r",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Available RAM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"nodeexporter\"}\r"
    }
   ]
  }
 ]
}